travis:
  secure:
    BINSTAR_TOKEN: VVbTp37KUVHBImHNZ9x91SRHeuPTsC6WD/2jhZyK0ZGIwNzf3/SxfA7s3HESVjoaQelVOby8r20zeyIsywsAGOYbLIVwuE9sgLczbAVhLAqftToQPjmjVg8tJLUgK6C7wQ6VfwLtzgnEQWxfwNQ9+nuw4opybAyOPH8h7jpue0aHlZL7Vl9UUa0tHYLbyPQZNV7aOhxos/U0Ds4461eEWHDq5936CdQRUq0+picrlDQaCufLLetOwNtS3VS/AxJhp0KDbGFAMqu0dKHpVlz9Dt2N0u6XSqzKFKjzYbztTB5BkWTh95+LzMsNC+BZxUqS5ytUShubglLo/9vUKFwtY0A2xq8HZu65JmEOGzBZ+LRRcwWP1MxCiH4fe/T5VgVldgsKoA1+zdebuojRiUsNWXXyWLKTLJgKCcddBpbRSZGmtJODsi1EF4HH3elxQyx74Gx8bBMQXofToQKgWqX9j9dC0aAjL9ejw/7HHInqXrZ2szXnqNyzZM+HPr/XC4BCRvCnQgqafyRxG7NOk3SD+svBo4XPDOaTur90ZT0aIauGhPuSQO0xmjNDLG73M/ucksBTi7h5qYrJCacMtLlYeNfS07WVvNGe+kQN4axN1Xk5sHexGBeJ2npav8Rh6IRow3WviP+ra2i22BOzA+5F2rytD4NDZGGryWJGAFSEQ0k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
