travis:
  secure:
    BINSTAR_TOKEN: j4L5DqxfPNS7OeyAbekGVpoOWkxot3cxnAf3TpP24OMh68v7g2l3MY20ZV5lJKAZMYiywJB+ILYkgsbZDv1/GMf2xK22yM5oWEK1s2GlF0DoxUTWiDYrs0J2r5QCNQ+KaZHhrS5lIMACCqdKqd7gw1NYc3fQCM9YCzPTvcAPQR433dqZeoH94l5R92lQ/9odfnqFOSsDLd00XdUCoRkbbKOHI+d5BvmVDN5RrHXqiHS+i/CwG2Mj8VstCaFX1bSxmJP2DCjU3NLG04fTxzkMss2qI9ip2xjCpTTG8d8mvYimwfdHz+51qJ+7pUD/QLkVTHdCkr/JPdSZT/T8R0ukrKX6yUarmncjDg+s4dR6XH4kd0Us1zj1HDjaNRjWJVBokTkSoEcVmfCs3sPqgcuEjFufcUgy1vmDCk/fknM/7gFrhGQQ+DeLf/Y8hOCHst8LKPC0BEUrYtSveQnvk6HyfnIifuLur7Aq+RvAdUiEQOgcC2aDSUlBkoC9i3VR/ezBYcEXnbd5UYzcoMW+hO3rOOSOQN4XUCzBpp5s1TFz5E+6ZIY5kLj4VUu5DVnDRhS7D4UD/4FfJa90WR16Hb9p7J/dyasRc0CwKSLcZV/3H5yx/6eY3fYoJ3/1wjUokh+hXke/5GdrlzzAQbaa1SGpkKVvcL1HjEe45nyZElTnxKY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
