travis:
  secure:
    BINSTAR_TOKEN: IrK7b69HXBxfgC8nKWoh0UO4J2VnpCdCS4AbZCB2zzf3ohNaqhTJ1DG8g461mMGDVfykZPC7delZQB7luvvgMcI5s2VMd3m/+zPmRLTLO6hHKmADAbHTSria9SBd7ANZ8Xn2WavKzo2bKmqfXrXSOL1jedTvmiZgWFXGxfbSGo81gKiaKBy8IfJC3E9A1vvyzRV+rc9MUb8rnnsPNtedGexseHOUmDAixwzVC2E94vTU0hNOYKdxUjmiF4RhfiAXFqltXznnvKRC0yfC1CjutKYvhmUeQmgkiQ8OX72QdMVNHq/x7Tj0PPIKxEEGCpPw9jfFnAS4r+kIGZT5WIMXLQ7bK8853N5wGQXiketg2Ho+1w/AtPvjLfg06oQb9V0bM/4LzuC57yYlyvw7Nz5H+lodtoHxmepG/0a6zk1l0HhSObHHqvQi5B2KxF7T5rIi8Kv/bDwdJOSGh9z1EfQXVJIWZhm/sqbC49leYqBjhq77y607FTKzYbDRxHOFqiCOX0+P0KCNDdcu4TQZS9UIvGs5bZ2oBLxA715+mb6YIH1Blw7Wam0CzVdCz7bLakxQlKiau5xuUuLYW++bD//OJUSSHaT8ttD/q1srBWMqKbW5fMR+r0xuzq0vYdRk7ekLEiarVV+K64HWF2CZX3uN6bVp5ZeS8+0bjikv4SJBO5E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
